/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: 'var(--color-brand)',
        success: 'var(--color-success)',
        danger: 'var(--color-danger)',
        duck: 'var(--color-duck-yellow)',
        canvas: 'var(--color-canvas)',
        'canvas-water': 'var(--color-canvas-water)',
        muted: 'var(--color-muted)',
        line: 'var(--color-line)',
        ink: 'var(--color-ink)',
        'surface-brand': 'var(--color-surface-brand)',
        'surface-brand-subtle': 'var(--color-surface-brand-subtle)',
        'surface-warm': 'var(--color-surface-warm)',
        'surface-success': 'var(--color-surface-success)',
        'surface-water': 'var(--color-surface-water)',
        'surface-brand-pale': 'var(--color-surface-brand-pale)',
        'line-brand': 'var(--color-line-brand)',
        'line-success': 'var(--color-line-success)',
        'brand-muted': 'var(--color-brand-muted)',
        'goal-loss': 'var(--color-goal-loss)',
        'goal-maintain': 'var(--color-goal-maintain)',
        'goal-gain': 'var(--color-goal-gain)',
        info: 'var(--color-info)',
        'plant-dot': 'var(--color-plant-dot)',
        'plant-dark': 'var(--color-plant-dark)',
        'plant-light': 'var(--color-plant-light)',
        food: 'var(--color-food)',
        'neutral-subtle': 'var(--color-neutral-subtle)',
        'water-line': 'var(--color-water-line)',
      },
      maxWidth: {
        screen: '390px',
      },
      borderRadius: {
        control: '10px',
        element: '14px',
        card: '20px',
        pill: '50px',
      },
      boxShadow: {
        card: '0 2px 16px rgba(0,0,0,0.04)',
        float: '0 2px 10px rgba(0,0,0,0.08)',
      },
      borderWidth: {
        1.5: '1.5px',
      },
    },
  },
  plugins: [],
};
